---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger
  labels:
    app: pinger
spec:
  selector:
    matchLabels:
      app: pinger
  replicas: 2
  template:
    metadata:
      labels:
        app: pinger
    spec:
      containers:
        - name: pinger
          image: zadenis/pinger:dev
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: pinger-service
spec:
  selector:
    app: pinger
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pinger-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pinger-service
            port:
              number: 8080
  ingressClassName: nginx
